/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#e8c179",
        "primary-container": "#b08d4b",
        "on-tertiary-fixed": "#271900",
        "surface-variant": "#e9e1dc",
        "tertiary-container": "#b48c3f",
        "secondary-fixed-dim": "#eebd93",
        "surface-dim": "#e0d9d3",
        "on-secondary-fixed": "#2d1600",
        tertiary: "#7a580c",
        "surface-container": "#f4ece7",
        "on-primary-fixed-variant": "#5d4204",
        primary: "#775a1c",
        "secondary-fixed": "#ffdcc0",
        "on-error": "#ffffff",
        "on-primary-fixed": "#271900",
        "on-background": "#1e1b18",
        "surface-container-low": "#faf2ed",
        "on-secondary-fixed-variant": "#613f1f",
        "surface-tint": "#775a1c",
        "on-secondary": "#ffffff",
        "error-container": "#ffdad6",
        "primary-fixed-dim": "#e8c179",
        surface: "#fff8f4",
        "on-tertiary-container": "#3b2800",
        "tertiary-fixed": "#ffdea7",
        "surface-bright": "#fff8f4",
        "on-tertiary-fixed-variant": "#5e4200",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#785431",
        "surface-container-high": "#eee7e1",
        "on-primary": "#ffffff",
        error: "#ba1a1a",
        "secondary-container": "#fdcb9f",
        "surface-container-highest": "#e9e1dc",
        "on-surface": "#1e1b18",
        "on-error-container": "#93000a",
        "inverse-surface": "#33302c",
        "on-primary-container": "#3a2800",
        "on-surface-variant": "#4e4639",
        secondary: "#7c5734",
        outline: "#7f7667",
        background: "#fff8f4",
        "primary-fixed": "#ffdea6",
        "outline-variant": "#d1c5b4",
        "inverse-on-surface": "#f7efea",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#edc06d",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-mobile": "1.25rem",
        gutter: "1.5rem",
        "space-lg": "1.5rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "gutter-mobile": "1rem",
        margin: "3rem",
        "space-xs": "0.25rem",
        "space-xl": "2.5rem",
      },
      fontFamily: {
        "headline-lg": ["Playfair Display", "serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Playfair Display", "serif"],
        "display-hero": ["Playfair Display", "serif"],
        "headline-sm": ["Playfair Display", "serif"],
        "headline-lg-mobile": ["Playfair Display", "serif"],
        "display-hero-mobile": ["Playfair Display", "serif"],
        "title-md": ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "title-md": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "500" }],
        "display-hero-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "label-sm": ["11px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "700" }],
        "headline-md": ["28px", { lineHeight: "36px", fontWeight: "500" }],
        "body-lg": ["16px", { lineHeight: "26px", fontWeight: "400" }],
        "headline-sm": ["22px", { lineHeight: "30px", fontWeight: "600" }],
        "label-md": ["13px", { lineHeight: "18px", letterSpacing: "0.04em", fontWeight: "600" }],
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "22px", fontWeight: "400" }],
        "display-hero": ["56px", { lineHeight: "64px", letterSpacing: "-0.02em", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
